# Theme
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "dark"

# Site settings
locale: "en"
title: "Gan Shijie"
title_separator: "|"
subtitle: "Computer Science at Monash University | Mechanical Engineering at Imperial College London"
name: "Gan Shijie"
description: "A portfolio of my projects and experiences."
url: "https://sgan0420.github.io"
masthead_title: "Shijie's Portfolio"
logo: "/assets/images/masthead_logo.png"
breadcrumbs: true
words_per_minute: 200
enable_copy_code_button: true

# Atom Feed Settings
atom_feed:
  hide: true

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

plugins:
  - jekyll-feed
  - jekyll-include-cache
