# Theme
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "dark"

# Site settings
locale: "en"
title: "My Portfolio"
title_separator: "|"
subtitle: "Computer Science | Mechanical Engineering | Software Development"
name: "Gan Shijie"
description: "A portfolio of my projects and experiences."
url: "https://sgan0420.github.io"


plugins:
  - jekyll-feed
  - jekyll-include-cache
